// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomEmojiServiceClient is the client API for CustomEmojiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomEmojiServiceClient interface {
	GetCustomEmojis(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CustomEmojis, error)
}

type customEmojiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomEmojiServiceClient(cc grpc.ClientConnInterface) CustomEmojiServiceClient {
	return &customEmojiServiceClient{cc}
}

func (c *customEmojiServiceClient) GetCustomEmojis(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CustomEmojis, error) {
	out := new(CustomEmojis)
	err := c.cc.Invoke(ctx, "/CustomEmojiService/GetCustomEmojis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomEmojiServiceServer is the server API for CustomEmojiService service.
// All implementations must embed UnimplementedCustomEmojiServiceServer
// for forward compatibility
type CustomEmojiServiceServer interface {
	GetCustomEmojis(context.Context, *emptypb.Empty) (*CustomEmojis, error)
	mustEmbedUnimplementedCustomEmojiServiceServer()
}

// UnimplementedCustomEmojiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomEmojiServiceServer struct {
}

func (UnimplementedCustomEmojiServiceServer) GetCustomEmojis(context.Context, *emptypb.Empty) (*CustomEmojis, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomEmojis not implemented")
}
func (UnimplementedCustomEmojiServiceServer) mustEmbedUnimplementedCustomEmojiServiceServer() {}

// UnsafeCustomEmojiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomEmojiServiceServer will
// result in compilation errors.
type UnsafeCustomEmojiServiceServer interface {
	mustEmbedUnimplementedCustomEmojiServiceServer()
}

func RegisterCustomEmojiServiceServer(s grpc.ServiceRegistrar, srv CustomEmojiServiceServer) {
	s.RegisterService(&CustomEmojiService_ServiceDesc, srv)
}

func _CustomEmojiService_GetCustomEmojis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEmojiServiceServer).GetCustomEmojis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomEmojiService/GetCustomEmojis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEmojiServiceServer).GetCustomEmojis(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomEmojiService_ServiceDesc is the grpc.ServiceDesc for CustomEmojiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomEmojiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CustomEmojiService",
	HandlerType: (*CustomEmojiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomEmojis",
			Handler:    _CustomEmojiService_GetCustomEmojis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/custom_emoji.proto",
}
