// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TimelineServiceClient is the client API for TimelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimelineServiceClient interface {
	GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error)
	GetAccountTimeline(ctx context.Context, in *AccountTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error)
	StreamTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (TimelineService_StreamTimelineClient, error)
}

type timelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimelineServiceClient(cc grpc.ClientConnInterface) TimelineServiceClient {
	return &timelineServiceClient{cc}
}

func (c *timelineServiceClient) GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error) {
	out := new(TimelineResponse)
	err := c.cc.Invoke(ctx, "/TimelineService/GetTimeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) GetAccountTimeline(ctx context.Context, in *AccountTimelineRequest, opts ...grpc.CallOption) (*TimelineResponse, error) {
	out := new(TimelineResponse)
	err := c.cc.Invoke(ctx, "/TimelineService/GetAccountTimeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) StreamTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (TimelineService_StreamTimelineClient, error) {
	stream, err := c.cc.NewStream(ctx, &TimelineService_ServiceDesc.Streams[0], "/TimelineService/StreamTimeline", opts...)
	if err != nil {
		return nil, err
	}
	x := &timelineServiceStreamTimelineClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TimelineService_StreamTimelineClient interface {
	Recv() (*Status, error)
	grpc.ClientStream
}

type timelineServiceStreamTimelineClient struct {
	grpc.ClientStream
}

func (x *timelineServiceStreamTimelineClient) Recv() (*Status, error) {
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TimelineServiceServer is the server API for TimelineService service.
// All implementations must embed UnimplementedTimelineServiceServer
// for forward compatibility
type TimelineServiceServer interface {
	GetTimeline(context.Context, *TimelineRequest) (*TimelineResponse, error)
	GetAccountTimeline(context.Context, *AccountTimelineRequest) (*TimelineResponse, error)
	StreamTimeline(*TimelineRequest, TimelineService_StreamTimelineServer) error
	mustEmbedUnimplementedTimelineServiceServer()
}

// UnimplementedTimelineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTimelineServiceServer struct {
}

func (UnimplementedTimelineServiceServer) GetTimeline(context.Context, *TimelineRequest) (*TimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedTimelineServiceServer) GetAccountTimeline(context.Context, *AccountTimelineRequest) (*TimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountTimeline not implemented")
}
func (UnimplementedTimelineServiceServer) StreamTimeline(*TimelineRequest, TimelineService_StreamTimelineServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTimeline not implemented")
}
func (UnimplementedTimelineServiceServer) mustEmbedUnimplementedTimelineServiceServer() {}

// UnsafeTimelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimelineServiceServer will
// result in compilation errors.
type UnsafeTimelineServiceServer interface {
	mustEmbedUnimplementedTimelineServiceServer()
}

func RegisterTimelineServiceServer(s grpc.ServiceRegistrar, srv TimelineServiceServer) {
	s.RegisterService(&TimelineService_ServiceDesc, srv)
}

func _TimelineService_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TimelineService/GetTimeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetTimeline(ctx, req.(*TimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_GetAccountTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetAccountTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TimelineService/GetAccountTimeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetAccountTimeline(ctx, req.(*AccountTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_StreamTimeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TimelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimelineServiceServer).StreamTimeline(m, &timelineServiceStreamTimelineServer{stream})
}

type TimelineService_StreamTimelineServer interface {
	Send(*Status) error
	grpc.ServerStream
}

type timelineServiceStreamTimelineServer struct {
	grpc.ServerStream
}

func (x *timelineServiceStreamTimelineServer) Send(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

// TimelineService_ServiceDesc is the grpc.ServiceDesc for TimelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TimelineService",
	HandlerType: (*TimelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimeline",
			Handler:    _TimelineService_GetTimeline_Handler,
		},
		{
			MethodName: "GetAccountTimeline",
			Handler:    _TimelineService_GetAccountTimeline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTimeline",
			Handler:       _TimelineService_StreamTimeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/timeline.proto",
}
